### ISSUE TITLE
Errors running tests: MPI already initialized

### ISSUE THREAD

**Issue by bhorowitz** [aslanyan/cosmopp#1]
I was able to successfully build cosmopp, and most tests run well. However, when running example_metropolis_hastings I get the following error.

CHECK FAILED in /global/homes/b/bhorowit/cosmopp/source/cosmo_mpi.cpp on line 14!!! MPI already initialized
Stopping execution!!!
MPI process 0 / 1:  EXCEPTION CAUGHT!!! 
CHECK FAILED
MPI process 0 / 1:  Terminating!

I'm uncertain what it means by MPI already initialized or why that is causing an issue in this instance?

**Comment by aslanyan** [comment]
Should be fixed now!
